language: python
python:
    - "3.6"

install:
  - pip install --upgrade typesense jsonschema

script:
  - python test-records.py

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then python deploy-typesense.py; fi'
