language: python
python:
  - '3.6'

install:
  - pip install --upgrade typesense jsonschema

script:
  - python test-records.py

deploy:
  - provider: script
    script: 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then python deploy-typesense.py; fi'
    on:
      branch: master
  # deploy non-master commits to a staging env, we may want to implement that in the future
  # - provider: script
  #   script: python deploy-typesense.py
  #   on:
  #     branch: develop
